# Generated by Django 3.1 on 2020-08-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='Bio',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time_required',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
